Make program work with espflash 4.x.x
The updated bootloader used by newer espflash requires an ESP-IDF App
Descriptor in the app.

Before fix:
```
cargo run
[...]
     Running `espflash flash --monitor --chip esp32c6 target/riscv32imac-unknown-none-elf/debug/esp32c6-hdc3022`
[2025-07-07T19:41:15Z INFO ] Serial port: '/dev/cu.usbserial-110'
[2025-07-07T19:41:15Z INFO ] Connecting...
[2025-07-07T19:41:16Z INFO ] Using flash stub
Error:   × ESP-IDF App Descriptor (https://docs.espressif.com/projects/esp-idf/en/stable/esp32/api-reference/system/app_image_format.html#application-description) missing in
  │ your`esp-idf` application.
```